### ISSUE TITLE
Empty OAuth2AccessToken is being injected due to SessionScoped being commented out in OAuth2StateHolder

### ISSUE THREAD

**Issue by NikitaZ** [payara/ecosystem-security-connectors#33]
Out of curiosity I've tried OAuth2AuthenticationDefinition (in production I'm using OpenID via GoogleAuthenticationDefinition) and found that whenever I inject OAuth2AccessToken it has empty values. After the authorization the values are set properly on OAuth2StateHolder by OAuth2AuthenticationMechanism and the root cause seems to be that @SessionScoped is commented out in the OAuth2StateHolder class:

//@SessionScoped
public class OAuth2StateHolder

in contrast to

@SessionScoped
public class OpenIdContextImpl implements OpenIdContext {
...
that's why a new OAuth2StateHolder is always injected!

I tried changing this (uncommenting @SessionScoped) and putting the resulted class file into
glassfish/modules/oauth2-client-integration.jar and it solved the problem.

**Comment by NikitaZ** [comment]
I can try to make a pull request for this or the other bug I filed, but I suspect it will cause more trouble than good, please, advice. I don't quite understand the relationship between this and the main payara repository.

**Comment by jGauravGupta** [comment]
Hi @NikitaZ,

I would applicate your help to fix the issue, please create the PR here: https://github.com/payara/Payara. After the Payara 5.202 release, [ecosystem-security-connectors](https://github.com/payara/ecosystem-security-connectors/) will be the main repository.

**Comment by NikitaZ** [comment]
Will do, thank you!

**Comment by NikitaZ** [comment]
Hi, @jGauravGupta, I created the pull request
https://github.com/payara/Payara/pull/4684

please, review
