### ISSUE TITLE
"expires_in" is not being parsed properly from the claims in OAuth2AuthenticationMechanism

### ISSUE THREAD

**Issue by NikitaZ** [payara/ecosystem-security-connectors#34]
I found that when OAuth2AuthenticationMechanism#validateCallback() parses "expires_in" claim it always gets null results. It should be using
    object.getJsonNumber("expires_in")
    instead of
            String expiresIn = object.getString("expires_in", null);
    the latter always returns null, while 
            object.getString("expires_in")
            results in ClassCastException
because expires_in is a number. 

Here's a sample of data I get from Google OAuth2:
{
  "access_token": "ya29.a0Af...Hl_9wzS0qno",
  "expires_in": 3587,
  "scope": "https://www.googleapis.com/auth/userinfo.email openid",
  "token_type": "Bearer",
  "id_token": "eyJhbGciOiJSU...gwsA538DNGRRw"
}

OpenIdAuthenticationMechanism had the same bug but it was fixed (unfortunately, few weeks after 5.201 release), see:

https://github.com/payara/ecosystem-security-connectors/commit/21d26d4b2cde70c4037a1f45eee594fa6e742946#diff-8749cd6264114355bbf67f0e15fddcf9
 -       String expiresIn = tokensObject.getString(EXPIRES_IN, null);
 +       JsonNumber expiresIn = tokensObject.getJsonNumber(EXPIRES_IN);
        if (nonNull(expiresIn)) {
 -          context.setExpiresIn(Integer.parseInt(expiresIn));
 +          context.setExpiresIn(expiresIn.longValue());

**Comment by NikitaZ** [comment]
I started wondering if this is the right place to file issues, should I file on https://github.com/payara/Payara Instead? I see ECOSYS-157 being pulled straight into Payara repository, but  ECOSYS-118 which fixes similar bug with OpenID is still not integrated there (ECOSYS-118 is what I'm really waiting for). That's confusing...

**Comment by jGauravGupta** [comment]
Hi @NikitaZ, 

Thanks for reporting the issue, this is the right place to report the issue for security-connector. Security Connectors source is moved in this repo and soon it will be removed from the Payara repository without any impact on Payara Server/Micro distributions.

**Comment by jGauravGupta** [comment]
As PR is already open for ECOSYS-118 and ECOSYS-157 and targeted for Payara 5.202. Hence closing this ticket.

**Comment by NikitaZ** [comment]
Hi @jGauravGupta,

I'm sorry if I am wrong, but I think ECOSYS-118 solves only OpenIdAuthenticationMechanism issue with "expires_in", the bug for OAuth2AuthenticationMechanism is still there. What do you think?

**Comment by NikitaZ** [comment]
To finish up (in case somebody would go through this issue later) it got covered in
https://github.com/payara/Payara/pull/4570
(https://github.com/payara/Payara/pull/4570/files/f660aa5a4b09f138fded6c0b985697e8a00b0163..c5a4900b3e1f812e240f54ee4b7ea6589e2fe66a)
